/**
 * NeoLocal Sales Engine — CRM v2.3 + Snapshot Intelligence Engine v2 (Realigned)
 * File: 00_config.gs
 */

const APP = {
  TZ: Session.getScriptTimeZone() || "America/Montreal",
  SHEETS: {
    SEARCH_CONFIG: "Search Config",
    LEADS: "Leads Master",
    IMPORT_LOG: "Import Log",
    SHADOW_JOBS: "Shadow Jobs"
  },
  MAX_RESULTS_PER_SEARCH: 20,
  TOP_COMPETITOR_COUNT: 5,
  SNAPSHOT_VERSION: "Snapshot Intelligence Engine v2.3 (Realigned)",
  LEAD_STATUS_DEFAULT: "New Lead",
  COUNTRIES: [
    "Canada",
    "United States"
  ],
  PROVINCES_STATES: [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Nova Scotia",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Northwest Territories",
    "Nunavut",
    "Yukon",
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
    "District of Columbia"
  ]
};